Allow you to call skip twice with the same name
embroider-build/scenario-tester pull request #30
Opened 2024-01-05 14:49 UTC by mansona

Before this change calling skip twice with the same name would throw an error: 

```
no variant named skipMe available to skip. Found variants: hello1, hello2
```

because the first time you called `.skip()` it removed it from the list of variants and the second time it would fail. This PR changes it so that it sets a flag `skipped` so the second time you call `.skip()` is essentially a no-op and won't fail.

This change is to allow you to skip variants globally without needing to also delete any specific skips you have in tests (see [this commit](https://github.com/embroider-build/embroider/pull/1653/commits/84961e2048e6fbc4772d8c45817dcb39c56da3ee) for an example)

2024-01-05 17:32 UTC, ef4 commented
There's a lot of `yarn` still in the test suite.

2024-01-05 17:59 UTC, ef4 requested changes
Just need to replace all the `yarn` calls in the test suite with `pnpm`, then this is looking good.

2024-01-06 23:50 UTC, mansona commented
@ef4 I got rid of all the yarn 👍 🧶

2024-01-07 02:24 UTC, ef4 approved these changes

2024-01-07 02:24 UTC, merged